import { StyleSheet } from "@react-pdf/renderer";

export const pdfStyles = StyleSheet.create({
  body: {
    paddingTop: 35,
    paddingBottom: 65,
    paddingHorizontal: 35,
    // height: "1267px",
  },
  name: {
    color: "#2A4879",
    fontSize: "20px",
    fontStyle: "normal",
    fontWeight: 800,
    lineHeight: "normal",
    textTransform: "uppercase",
  },
  contactInfo: {
    color: "#000",
    fontSize: "10px",
    fontStyle: "normal",
    fontWeight: 500,
    lineHeight: "normal",
    textDecoration: "none",
    display: "flex",
  },
  personalInfo: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
  },
  professionalTitle: {
    display: "flex",
    flexDirection: "column",
    backgroundColor: "#405F8D",
    alignItems: "center",
    marginTop: "14px",
    padding: "8px 16px",
  },
  sectionTitle: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    padding: "5px 0px",
    backgroundColor: "#405F8D",
    marginTop: "6px",
  },
  sectionTitleText: {
    color: "white",
    fontSize: "14px",
    fontStyle: "normal",
    fontWeight: 800,
    lineHeight: "normal",
  },
  lightBlueColor: {
    backgroundColor: "#DDE4F0",
    padding: "5px",
    borderLeft: "1px solid #526130",
    borderRight: "1px solid #526130",
    borderTop: "1px solid #526130",
  },
  coreCompetencies: {
    display: "flex",
    flexDirection: "column",
  },
  competenciesContent: {
    marginTop: "8px",
    display: "flex",
    flexDirection: "row",
    flexWrap: "wrap",
  },
  item: {
    maxWidth: "40%",
    flexBasis: "33.33%",
    color: "#000",
    fontSize: "10px",
    fontStyle: "normal",
    fontWeight: 400,
    lineHeight: "1.31",
  },
  professionalSummary: {
    color: "#000",
    fontSize: "10px",
    fontStyle: "normal",
    fontWeight: 400,
    lineHeight: "131.31%",
    marginTop: "6px",
    marginBottom: "6px",
  },
  professionalTitleText: {
    color: "black",
    fontSize: "14px",
    fontStyle: "normal",
    fontWeight: 800,
    lineHeight: "normal",
    textAlign: "justify",
  },
  professionalTitleSubText: {
    color: "black",
    textAlign: "center",
    fontSize: "12px",
    fontStyle: "normal",
    fontWeight: 600,
    lineHeight: "normal",
    marginTop: "8px",
  },
  bulletPoint: {
    color: "#000",
    fontSize: "10px",
    fontStyle: "normal",
    fontWeight: 400,
    lineHeight: "150%",
    display: "flex",
    flexDirection: "row",
  },
  lightBlueSectionText: {
    color: "#000",
    fontSize: "10px",
    // fontStyle: "italic",
    fontWeight: 500,
    lineHeight: "131.31%",
  },
  competenciesTitleText: {
    color: "#000",
    fontSize: "14px",
    fontStyle: "normal",
    fontWeight: 800,
    lineHeight: "normal",
  },
  experienceSec: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    flexDirection: "row",
    flexWrap: "wrap",
    width: "100%",
  },
  experienceSecText: {
    color: "#000",
    display: "flex",
    fontSize: "12px",
    fontStyle: "normal",
    fontWeight: 700,
    lineHeight: "131.31%",
    marginTop: "5px",
    marginBottom: "5px",
    paddingLeft: "5px",
  },
  remoteText: {
    color: "#000",
    fontSize: "12px",
    fontStyle: "normal",
    fontWeight: 500,
    lineHeight: "131.31%",
    display: "flex",
    marginTop: "5px",
    marginBottom: "5px",
  },
  centerAlignedText: {
    display: "flex",
    flexDirection: "row",
    color: "#000",
    fontSize: "10px",
    fontStyle: "normal",
    fontWeight: 400,
    lineHeight: "150%",
    alignItems: "center",
    justifyContent: "center",
    textAlign: "center",
  },
  bulletPadding: {
    paddingLeft: "8px",
  },
  dateClass: {
    width: "30%",
    height: "100%",
    justifyContent: "flex-start",
    alignItems: "flex-end",
  },
  gpaText: {
    color: "#000",
    fontFamily: "Inter",
    fontSize: "10px",
    fontStyle: "normal",
    fontWeight: 400,
    lineHeight: "150%",
    marginBottom: "3px",
  },
});
